[{
    "text": "Before each of your turns, if there is a Match in play, you get 1 more Action that turn.",
    "set": "chamberOfSecrets",
    "number": "1",
    "name": "Angelina Johnson",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Witch", "Gryffindor", "Unique"],
    "id": 328
}, {
    "text": "Once per turn, you may use an Action to choose 1 of your Items in play and do damage to your opponent equal to its printed Power cost.",
    "set": "chamberOfSecrets",
    "number": "2",
    "name": "Arthur Weasley",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Unique"],
    "id": 329
}, {
    "text": "Do 8 damage to your opponent. Then, if your opponent has any cards in play (other than his or her starting Character), he or she chooses 1 of them and discards it.",
    "set": "chamberOfSecrets",
    "number": "3",
    "name": "Blagging",
    "rarity": "Rare",
    "cost": "11Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 330
}, {
    "text": "Do 8 damage to your opponent. Then your opponent may choose a Lesson card from his or her hand and discard it. If he or she does, you take 8 damage.",
    "set": "chamberOfSecrets",
    "number": "4",
    "name": "Body Blow",
    "rarity": "Rare",
    "cost": "7Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 331
}, {
    "text": "You may use an Action to reveal the top card of your deck. If it's a Lesson card, put it into play. If it isn't a Lesson card, discard it. If you play this card, and you already have a Wand in play, discard the old one. Provide:",
    "set": "chamberOfSecrets",
    "number": "5",
    "name": "Broken Wand",
    "rarity": "Rare",
    "cost": "2C",
    "power": "1C",
    "type": "Item",
    "groupBlock": "item",
    "descriptors": ["Wand"],
    "id": 332
}, {
    "text": "When you play this card, discard any other Location from play (yours or your opponent's). Before each player's turn, if that player has fewer than 4 cards in his or her hand, that player draws cards until he or she has 4.",
    "set": "chamberOfSecrets",
    "number": "6",
    "name": "The Burrow",
    "rarity": "Rare",
    "cost": "5C",
    "type": "Location",
    "groupBlock": "location",
    "descriptors": ["Unique"],
    "id": 333
}, {
    "text": "Once per turn, you may use an Action to draw 3 cards and then make your opponent draw 3 cards.",
    "set": "chamberOfSecrets",
    "number": "7",
    "name": "Colin Creevey",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Gryffindor", "Unique"],
    "id": 334
}, {
    "text": "When you play this card, draw a card.Damage: 3 Health: 3",
    "set": "chamberOfSecrets",
    "number": "8",
    "name": "Crazed Capybara",
    "rarity": "Rare",
    "cost": "7F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Capybara"],
    "id": 335
}, {
    "text": "Play this card only if you have at least 5 Lessons in play. Effect: At the end of each of your opponent's turns, if he or she has any cards in his or her hand, he or she chooses 1 of them and discards it. To Solve: Your opponent discards 5 cards in this way. Opponent's Reward: Your opponent may draw a card.",
    "set": "chamberOfSecrets",
    "number": "9",
    "name": "De-Gnoming the Garden",
    "rarity": "Rare",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 336
}, {
    "text": "Choose 1 of your opponent's cards in play (other than his or her starting Character) and return it to his or her hand. You get 1 more Action this turn.",
    "set": "chamberOfSecrets",
    "number": "10",
    "name": "Dobby's Disappearance",
    "rarity": "Rare",
    "cost": "4T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 337
}, {
    "text": "Your opponent draws 10 cards.",
    "set": "chamberOfSecrets",
    "number": "11",
    "name": "Dobby's Help",
    "rarity": "Rare",
    "cost": "10C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 338
}, {
    "text": "To play this card, discard 2 other cards from your hand. Do 5 damage to your opponent. Then, if your opponent has any cards in his or her hand, he or she chooses 2 of them and discards them (1 if he or she has only 1).",
    "set": "chamberOfSecrets",
    "number": "12",
    "name": "Double-Beater Defence",
    "rarity": "Rare",
    "cost": "8Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 339
}, {
    "text": "If your opponent has any cards in his or her hand, you may use an Action to make him or her choose 1 of them and discard it.",
    "set": "chamberOfSecrets",
    "number": "13",
    "name": "Draco the Seeker",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Slytherin", "Unique"],
    "id": 340
}, {
    "text": "To play this card, return 2 of you: Lessons from play to your hand. Do 10 damage to your opponent or to a Creature of your choice.",
    "set": "chamberOfSecrets",
    "number": "14",
    "name": "Dragon Poison",
    "rarity": "Rare",
    "cost": "7P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 341
}, {
    "text": "When you play this card, discard any other Location from play (yours or your opponent's). All Item cards (yours and your opponent's) need 3 less Power to play. (You still need at least 1 Power that matches.)",
    "set": "chamberOfSecrets",
    "number": "15",
    "name": "Dumbledore's Office",
    "rarity": "Rare",
    "cost": "5T",
    "type": "Location",
    "groupBlock": "location",
    "descriptors": ["Unique"],
    "id": 342
}, {
    "text": "Search your deck. You may take a Character card from your deck, show it to your opponent and put it into your hand. Then shuffle your deck.",
    "set": "chamberOfSecrets",
    "number": "16",
    "name": "Entrancing Enchantments",
    "rarity": "Rare",
    "cost": "2C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 343
}, {
    "text": "When you play this card, reveal the top card of your deck. If it's a Lesson card, put it into play. If it isn't, put it back on top of your deck.Damage: 1 Health: 1",
    "set": "chamberOfSecrets",
    "number": "17",
    "name": "Errol",
    "rarity": "Rare",
    "cost": "3F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Owl", "Unique"],
    "id": 344
}, {
    "text": "Effect: Your opponent can't use Actions to play non-Lesson cards. To Solve: Your opponent discards his or her hand. Opponent's Reward: Your opponent searches his or her deck for any card, puts it into his or her hand and then shuffles his or her deck.",
    "set": "chamberOfSecrets",
    "number": "18",
    "name": "Escaping the Dursleys",
    "rarity": "Rare",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 345
}, {
    "text": "Once per game, you may draw 2 cards, then do 2 damage to your opponent and then put up to 2 non-Healing cards from your discard pile on the bottom of your deck.",
    "set": "chamberOfSecrets",
    "number": "19",
    "name": "Fat Friar",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Ghost", "Hufflepuff", "Unique"],
    "id": 346
}, {
    "text": "Each turn, you may prevent 4 damage done to you. If Fawkes is discarded from play, put it into your hand.Damage: 0 Health: 4",
    "set": "chamberOfSecrets",
    "number": "20",
    "name": "Fawkes",
    "rarity": "Rare",
    "cost": "12F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Phoenix", "Unique"],
    "id": 347
}, {
    "text": "Play this card only if you have at least 7 Lessons in play. Effect: Before each of your turns, your opponent takes 5 damage. To Solve: Your opponent chooses 4 of his or her cards in play (other than his or her starting Character) and discards them. Opponent's Reward: You take 5 damage.",
    "set": "chamberOfSecrets",
    "number": "21",
    "name": "Fighting the Basilisk",
    "rarity": "Rare",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 348
}, {
    "text": "You may use an Action to choose an Adventure or a Location in play and discard it. (If you discard an Adventure, you don't get the reward.)",
    "set": "chamberOfSecrets",
    "number": "22",
    "name": "Flying Car",
    "rarity": "Rare",
    "cost": "8C",
    "type": "Item",
    "groupBlock": "item",
    "id": 349
}, {
    "text": "Count the number of Lessons you have in play. Do that much damage to your opponent. Then draw that many cards.",
    "set": "chamberOfSecrets",
    "number": "23",
    "name": "Flying Laps",
    "rarity": "Rare",
    "cost": "10Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 350
}, {
    "text": "Effect: Before each of your turns, your opponent takes 2 damage. To Solve: Your opponent skips a total of 5 Actions. (They don't need to be one right after the other.) Opponent's Reward: Your opponent may look at your hand, choose 1 of those cards and discard it.",
    "set": "chamberOfSecrets",
    "number": "24",
    "name": "Flying to Hogwarts",
    "rarity": "Rare",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 351
}, {
    "text": "Before each of your turns, count the number of other Characters you have in play. You may draw that many cards.",
    "set": "chamberOfSecrets",
    "number": "25",
    "name": "Ginny Weasley",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Witch", "Gryffindor", "Unique"],
    "id": 352
}, {
    "text": "When you play this card, discard any other Location from play (yours or your opponent's). Once during each player's turn, when he or she uses an Action to play a Plant card, he or she gets 1 more Action that turn.",
    "set": "chamberOfSecrets",
    "number": "26",
    "name": "Greenhouse Three",
    "rarity": "Rare",
    "cost": "3F",
    "type": "Location",
    "groupBlock": "location",
    "descriptors": ["Unique"],
    "id": 353
}, {
    "text": "When you play this card, discard any other Location from play (yours or your opponent's). Before each player's turn, he or she counts the number of Gryffindor cards he or she has in play and may draw that many cards.",
    "set": "chamberOfSecrets",
    "number": "27",
    "name": "Gryffindor Common Room",
    "rarity": "Rare",
    "cost": "5T",
    "type": "Location",
    "groupBlock": "location",
    "descriptors": ["Gryffindor", "Unique"],
    "id": 354
}, {
    "text": "At the start of the game, if Harry, Second Year is your starting Character, secretly write down the name of a Creature, Item or Spell card. If your opponent plays that card, you may reveal what you wrote down. If you do, at the end of that turn, you may shuffle up to 20 non-Healing cards from your discard pile into your deck.",
    "set": "chamberOfSecrets",
    "number": "28",
    "name": "Harry, Second Year",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Gryffindor", "Unique"],
    "id": 355
}, {
    "text": "You may use an Action to put up to 2 Lesson cards of different types from your hand into play.",
    "set": "chamberOfSecrets",
    "number": "29",
    "name": "Hermione, Potion Maker",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Witch", "Gryffindor", "Unique"],
    "id": 356
}, {
    "text": "Choose a Character in play (other than a starting Character) and discard it. Then search your deck. You may take a Character card from your deck, show it to your opponent and put it into your hand. Then shuffle your deck.",
    "set": "chamberOfSecrets",
    "number": "30",
    "name": "Impersonating Goyle",
    "rarity": "Rare",
    "cost": "5P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 357
}, {
    "text": "Effect: Before each of your turns, you may show your opponent any number of Creature cards from your hand. Your opponent takes that much damage. To Solve: Your opponent takes 10 damage. Opponent's Reward: If you have any cards in your hand, you choose 1 of them and discard it.",
    "set": "chamberOfSecrets",
    "number": "31",
    "name": "In the Spider's Lair",
    "rarity": "Rare",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 358
}, {
    "text": "You may use an Action to draw 2 cards and then put 2 cards from your hand on the bottom of your deck (in any order).",
    "set": "chamberOfSecrets",
    "number": "32",
    "name": "Justin Finch-Fletchley",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Hufflepuff", "Unique"],
    "id": 359
}, {
    "text": "Effect: Whenever you use an Action to play a Spell, your opponent says 'Brilliant!' If your opponent forgets, he or she takes 3 damage at the end of that turn. To Solve: Your opponent lets you have 4 more Actions on your next turn. Opponent's Reward: You take 3 damage.",
    "set": "chamberOfSecrets",
    "number": "33",
    "name": "Lockhart's Lecture",
    "rarity": "Rare",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 360
}, {
    "text": "You may use an Action and discard Mandrake from play to put a non-Healing Character card from your discard pile into your hand.Damage: 3   Health: 1",
    "set": "chamberOfSecrets",
    "number": "34",
    "name": "Mandrake",
    "rarity": "Rare",
    "cost": "5F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Plant"],
    "id": 361
}, {
    "text": "Your opponent chooses 1 card in his or her hand and discards the rest.",
    "set": "chamberOfSecrets",
    "number": "35",
    "name": "Memory Charm",
    "rarity": "Rare",
    "cost": "9C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 362
}, {
    "text": "When you play this card, discard any other Location from play (yours or your opponent's). Before each player's turn, if he or she has at least 2 Characters in play (including his or her starting Character), he or she gets 1 more Action that turn.",
    "set": "chamberOfSecrets",
    "number": "36",
    "name": "Moaning Myrtle's Bathroom",
    "rarity": "Rare",
    "cost": "5P",
    "type": "Location",
    "groupBlock": "location",
    "descriptors": ["Unique"],
    "id": 363
}, {
    "text": "You may use an Action to search your deck. You may take a Character card for a Weasley character from your deck, show it to your opponent and put it into your hand. Then shuffle your deck.",
    "set": "chamberOfSecrets",
    "number": "37",
    "name": "Molly Weasley",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Witch", "Unique"],
    "id": 364
}, {
    "text": "Whenever one of your Quidditch Spells does damage to your opponent, it does 3 more damage. If you play this card, and you already have a Broom in play, discard the old one.",
    "set": "chamberOfSecrets",
    "number": "38",
    "name": "Nimbus Two Thousand and One",
    "rarity": "Rare",
    "cost": "9Q",
    "type": "Item",
    "groupBlock": "item",
    "descriptors": ["Broom"],
    "id": 365
}, {
    "text": "Play this card only if there is a Match in play. Discard the top card of your deck. If that card is a Lesson card, you win the current Match (you get the prize). Otherwise, you take 3 damage.",
    "set": "chamberOfSecrets",
    "number": "39",
    "name": "No Hands",
    "rarity": "Rare",
    "cost": "3Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 366
}, {
    "text": "To play this card, return 2 of you: Lessons from play to your hand. <p>Damage: 7   Health: 5</p>",
    "set": "chamberOfSecrets",
    "number": "40",
    "name": "Norwegian Ridgeback",
    "rarity": "Rare",
    "cost": "8F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Dragon"],
    "id": 367
}, {
    "text": "At the end of each of your opponent's turns, if he or she played a non-Lesson card that turn, he or she takes 1 damage.",
    "set": "chamberOfSecrets",
    "number": "41",
    "name": "Percy Weasley",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Gryffindor", "Unique"],
    "id": 368
}, {
    "text": "Choose 1 of your opponent's Creatures or Characters in play (other than his or her starting Character) and put it on the bottom of his or her deck.",
    "set": "chamberOfSecrets",
    "number": "42",
    "name": "Petrified",
    "rarity": "Rare",
    "cost": "7T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 369
}, {
    "text": "To play this card, return 4 of you:  Lessons from play to your hand. Shuffle up to 16 non-Healing cards from your discard pile into your deck.",
    "set": "chamberOfSecrets",
    "number": "43",
    "name": "Phoenix Tears",
    "rarity": "Rare",
    "cost": "10P",
    "type": "Spell",
    "groupBlock": "spell",
    "descriptors": ["Healing"],
    "id": 370
}, {
    "text": "Your opponent takes damage until he or she discards a total of 3 Lesson cards from his or her deck.",
    "set": "chamberOfSecrets",
    "number": "44",
    "name": "Potions Test",
    "rarity": "Rare",
    "cost": "12P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 371
}, {
    "text": "Each of your Plants has 2 more Health. Provide:",
    "set": "chamberOfSecrets",
    "number": "45",
    "name": "Professor Pomona Sprout",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Witch", "Hufflepuff", "Unique:"],
    "id": 372
}, {
    "text": "Put a non-Healing card from your discard pile into your hand.",
    "set": "chamberOfSecrets",
    "number": "46",
    "name": "Reparo",
    "rarity": "Rare",
    "cost": "7C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 373
}, {
    "text": "Before each of your turns, your opponent takes 3 damage.",
    "set": "chamberOfSecrets",
    "number": "47",
    "name": "Rogue Bludger",
    "rarity": "Rare",
    "cost": "8Q",
    "type": "Item",
    "groupBlock": "item",
    "id": 374
}, {
    "text": "If you have no cards in your hand, you may use an Action to draw 5 cards.",
    "set": "chamberOfSecrets",
    "number": "48",
    "name": "Ron, Youngest Brother",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Gryffindor", "Unique"],
    "id": 375
}, {
    "text": "Search your deck. You may take up to 2 Creature cards from your deck, show them to your opponent and put them into your hand. Then shuffle your deck.",
    "set": "chamberOfSecrets",
    "number": "49",
    "name": "Serpensortia",
    "rarity": "Rare",
    "cost": "6T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 376
}, {
    "text": "When you play this card, discard any other Location from play (yours or your opponent's). Before each player's turn, he or she counts the number of Slytherin cards he or she has in play and does that much damage to his or her opponent",
    "set": "chamberOfSecrets",
    "number": "50",
    "name": "Slytherin Common Room",
    "rarity": "Rare",
    "cost": "5P",
    "type": "Location",
    "groupBlock": "location",
    "descriptors": ["Slytherin", "Unique"],
    "id": 377
}, {
    "text": "Return all Creatures in play (yours and your opponent's) to their owners' hands.",
    "set": "chamberOfSecrets",
    "number": "51",
    "name": "Spiders' Exodus",
    "rarity": "Rare",
    "cost": "6T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 378
}, {
    "text": "Count the number of cards in your opponent's hand. He or she draws twice that many cards.",
    "set": "chamberOfSecrets",
    "number": "52",
    "name": "Venomous Tentacular Juice",
    "rarity": "Rare",
    "cost": "9P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 379
}, {
    "text": "Before each of your turns, if you have an Adventure in play, your opponent takes 2 damage.",
    "set": "chamberOfSecrets",
    "number": "53",
    "name": "The Weasley Twins",
    "rarity": "Rare",
    "type": "Character",
    "groupBlock": "character",
    "descriptors": ["Wizard", "Gryffindor", "Unique"],
    "id": 380
}, {
    "text": "To play this card, return 3 of you: Lessons from play to your hand. Before each of your turns, if your opponent has any Items in play, choose 1 of them and discard it. Damage: 8  Health: 12",
    "set": "chamberOfSecrets",
    "number": "54",
    "name": "Whomping Willow",
    "rarity": "Rare",
    "cost": "9F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Plant", "Unique"],
    "id": 381
}, {
    "text": "You may use an Action and discard 1 of your Lessons from play to do 2 damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "55",
    "name": "Wizards Chess",
    "rarity": "Rare",
    "cost": "6T",
    "type": "Item",
    "groupBlock": "item",
    "id": 382
}, {
    "text": "To play this card, return 2 of: Lessons from play to your hand. Do 7 damage to your opponent or to a Creature of your choice.",
    "set": "chamberOfSecrets",
    "number": "56",
    "name": "Angel's Trumpet Draught",
    "rarity": "Uncommon",
    "cost": "4P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 383
}, {
    "text": "Draw 4 cards. Then your opponent may choose a Lesson card from his or her hand and discard it. If he or she does, you choose 3 cards in your hand and discard them.",
    "set": "chamberOfSecrets",
    "number": "57",
    "name": "Blocked!",
    "rarity": "Uncommon",
    "cost": "5Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 384
}, {
    "text": "Effect: Your opponent can't use Actions to play Location cards. To Solve: Your opponent chooses 2 Location cards in his or her hand and discards them. Opponent's Reward: Once during this turn, when your opponent uses an Action to play a Location card, he or she gets 2 more Actions this turn.",
    "set": "chamberOfSecrets",
    "number": "58",
    "name": "Blocked Barrier",
    "rarity": "Uncommon",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 385
}, {
    "text": "Your opponent chooses 1 of his or her Creatures or Items in play and discards it. Then he or she takes damage equal to that card's printed Power cost.",
    "set": "chamberOfSecrets",
    "number": "59",
    "name": "Bundimun Ooze",
    "rarity": "Uncommon",
    "cost": "5P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 386
}, {
    "text": "Choose 1 of your opponent's cards in play (other than his or her starting Character) and discard it. Your opponent may prevent this by choosing 4 cards in his or her hand and discarding them.",
    "set": "chamberOfSecrets",
    "number": "60",
    "name": "Caught!",
    "rarity": "Uncommon",
    "cost": "6T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 387
}, {
    "text": "Effect: Your opponent can't use Actions to play any cards except Lesson cards. To Solve: Your opponent uses Actions to play Lesson cards 3 times. (Those Actions don't need to be one right after the other.) Opponent's Reward: Your opponent may put any number of Lesson cards from his or her hand into play.",
    "set": "chamberOfSecrets",
    "number": "61",
    "name": "Caught by Snape",
    "rarity": "Uncommon",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 388
}, {
    "text": "Do 4 damage to your opponent. Then your opponent may choose a Lesson card in his or her hand and discard it. If he or she does, you take 4 damage.",
    "set": "chamberOfSecrets",
    "number": "62",
    "name": "Checked!",
    "rarity": "Uncommon",
    "cost": "3Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 389
}, {
    "text": "When you play this card, look at the top 2 cards of your deck (1 if there is only 1) and put both of them on the bottom or back on the top of your deck in any order. If you play this card, and you already have a Broom in play, discard the old one.",
    "set": "chamberOfSecrets",
    "number": "63",
    "name": "Cleansweep Five",
    "rarity": "Uncommon",
    "cost": "5Q",
    "type": "Item",
    "groupBlock": "item",
    "descriptors": ["Broom"],
    "id": 390
}, {
    "text": "Choose 1 of your opponent's Creatures in play and put it on the bottom of his or her deck.",
    "set": "chamberOfSecrets",
    "number": "64",
    "name": "Counter Curse",
    "rarity": "Uncommon",
    "cost": "5T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 391
}, {
    "text": "Before each of your turns, count the number of Plants you have in play. Do that much damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "65",
    "name": "Dragon-Dung Compost",
    "rarity": "Uncommon",
    "cost": "7F",
    "type": "Item",
    "groupBlock": "item",
    "id": 392
}, {
    "text": "Once during each of your turns, you may choose 1 of your opponent's Creatures in play. Prevent up to 3 damage from that Creature on your opponent's next turn.",
    "set": "chamberOfSecrets",
    "number": "66",
    "name": "Earmuffs",
    "rarity": "Uncommon",
    "cost": "7F",
    "type": "Item",
    "groupBlock": "item",
    "id": 393
}, {
    "text": "Play this card only if you have fewer than 7 other cards in your hand. Draw cards until you have 7 cards in your hand.",
    "set": "chamberOfSecrets",
    "number": "67",
    "name": "Endless Sandwiches",
    "rarity": "Uncommon",
    "cost": "7C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 394
}, {
    "text": "Search your deck. You may take a Location card from your deck, show it to your opponent and put it into your hand. Then shuffle your deck.",
    "set": "chamberOfSecrets",
    "number": "68",
    "name": "Floo Powder",
    "rarity": "Uncommon",
    "cost": "2T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 395
}, {
    "text": "During your opponent's next turn, he or she can't use Actions to play Lesson cards.",
    "set": "chamberOfSecrets",
    "number": "69",
    "name": "Forgotten Password",
    "rarity": "Uncommon",
    "cost": "6C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 396
}, {
    "text": "Choose 1 of your opponent's cards in play (other than his or her starting Character) and discard it. Then he or she chooses 1 of your cards in play (other than your starting Character) and discards it.",
    "set": "chamberOfSecrets",
    "number": "70",
    "name": "Invisibility Section",
    "rarity": "Uncommon",
    "cost": "4T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 397
}, {
    "text": "Effect: Your opponent discards the card drawn at the start of each of his or her turns. To Solve: Your opponent takes 8 damage. Opponent's Reward: You take 2 damage.",
    "set": "chamberOfSecrets",
    "number": "71",
    "name": "Keeping Dobby Quiet",
    "rarity": "Uncommon",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 398
}, {
    "text": "Effect: Your opponent gets 1 fewer Action on each of his or her turns (even the turn this Adventure is solved). (If this would mean your opponent has fewer than 1 Action, he or she still gets 1 Action.) To Solve: Your opponent chooses 4 cards in his or her hand and discards them. Opponent's Reward: Your opponent may draw 2 cards.",
    "set": "chamberOfSecrets",
    "number": "72",
    "name": "Locked In",
    "rarity": "Uncommon",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 399
}, {
    "text": "Whenever you play a Character card, you use up 1 Action to play it instead of 2.",
    "set": "chamberOfSecrets",
    "number": "73",
    "name": "Lockhart's Hair-Care Potions",
    "rarity": "Uncommon",
    "cost": "1P",
    "type": "Item",
    "groupBlock": "item",
    "id": 400
}, {
    "text": "Choose any number of your cards in play (other than your starting Character) and discard them.",
    "set": "chamberOfSecrets",
    "number": "74",
    "name": "Magical Mess Remover",
    "rarity": "Uncommon",
    "cost": "1P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 401
}, {
    "text": "Damage: 2   Health: 4",
    "set": "chamberOfSecrets",
    "number": "75",
    "name": "Manticore",
    "rarity": "Uncommon",
    "cost": "5F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Manticore"],
    "id": 402
}, {
    "text": "Your opponent takes damage until he or she discards a total of 2 Lesson cards from his or her deck.",
    "set": "chamberOfSecrets",
    "number": "76",
    "name": "Potions Project",
    "rarity": "Uncommon",
    "cost": "5P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 403
}, {
    "text": "When you play this card, draw a card. Damage: 2   Health: 2",
    "set": "chamberOfSecrets",
    "number": "77",
    "name": "Prickly Porcupine",
    "rarity": "Uncommon",
    "cost": "5F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Porcupine"],
    "id": 404
}, {
    "text": "When you play this card, play it face down and tell your opponent to guess 'Pure-Blood', 'Sherbet Lemon' or 'Wattlebird'. If he or she guesses 'Pure-Blood', nothing happens. Otherwise, do 8 damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "78",
    "name": "Pure-Blood",
    "rarity": "Uncommon",
    "cost": "6C",
    "type": "Spell",
    "groupBlock": "spell",
    "descriptors": ["Password"],
    "id": 405
}, {
    "text": "Choose up to 2 Creatures in play and discard them.",
    "set": "chamberOfSecrets",
    "number": "79",
    "name": "Rabbit Slippers",
    "rarity": "Uncommon",
    "cost": "8T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 406
}, {
    "text": "To Win: Do 9 damage to your opponent. (That damage doesn't have to be done all at once.) Prize: Winner shuffles up to 6 non-Healing cards from his or her discard pile into his or her deck.",
    "set": "chamberOfSecrets",
    "number": "80",
    "name": "Rainy-Day Match",
    "rarity": "Uncommon",
    "cost": "1Q",
    "type": "Match",
    "groupBlock": "match",
    "id": 407
}, {
    "text": "When you play this card, discard any other Location from play (yours or your opponent's). Whenever a Spell card (yours or your opponent's) does damage to a player, it does 1 less damage to that player.",
    "set": "chamberOfSecrets",
    "number": "81",
    "name": "Second-Hand Robe Shop",
    "rarity": "Uncommon",
    "cost": "3T",
    "type": "Location",
    "groupBlock": "location",
    "id": 408
}, {
    "text": "You may use an Action to have both players shuffle their decks.",
    "set": "chamberOfSecrets",
    "number": "82",
    "name": "Self-Shuffling Cards",
    "rarity": "Uncommon",
    "cost": "3C",
    "type": "Item",
    "groupBlock": "item",
    "id": 409
}, {
    "text": "When you play this card, play it face down and tell your opponent to guess 'Pure-Blood', 'Sherbet Lemon' or 'Wattlebird'. If he or she guesses 'Sherbet Lemon', nothing happens. Otherwise, do 8 damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "83",
    "name": "Sherbet Lemon",
    "rarity": "Uncommon",
    "cost": "6C",
    "type": "Spell",
    "groupBlock": "spell",
    "descriptors": ["Password"],
    "id": 410
}, {
    "text": "Do 8 damage to your opponent. He or she can prevent this by choosing 3 cards in his or her hand and discarding them.",
    "set": "chamberOfSecrets",
    "number": "84",
    "name": "Swelling Solution",
    "rarity": "Uncommon",
    "cost": "7P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 411
}, {
    "text": "Effect: Before each of your opponent's turns, he or she draws 3 cards and then chooses 3 cards in his or her hand and discards them. To Solve: Your opponent chooses 1 of his or her Locations in play or 4 of his or her Lessons in play and discards them. Opponent's Reward: You take 3 damage.",
    "set": "chamberOfSecrets",
    "number": "85",
    "name": "Through the Floo",
    "rarity": "Uncommon",
    "type": "Adventure",
    "groupBlock": "adventure",
    "id": 412
}, {
    "text": "Do 5 damage to your opponent. Then, if he or she has any cards in play other than Lessons (or his or her starting Character), he or she chooses 1 of those cards and returns it to his or her hand.",
    "set": "chamberOfSecrets",
    "number": "86",
    "name": "Twirl",
    "rarity": "Uncommon",
    "cost": "8Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 413
}, {
    "text": "Once per turn, you may let Umbrella Flowers take 1 damage that you were going to take. Damage: 0  Health: 6",
    "set": "chamberOfSecrets",
    "number": "87",
    "name": "Umbrella Flowers",
    "rarity": "Uncommon",
    "cost": "3F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Plant"],
    "id": 414
}, {
    "text": "You may use an Action and discard Venomous Tentacula from play to put: Lesson from your discard pile into play.<p>Damage: 2  Health: 1</p>",
    "set": "chamberOfSecrets",
    "number": "88",
    "name": "Venomous Tentacula",
    "rarity": "Uncommon",
    "cost": "4F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Plant"],
    "id": 415
}, {
    "text": "When you play this card, play it face down and tell your opponent to guess 'Pure-Blood', 'Sherbet Lemon' or 'Wattlebird'. If he or she guesses 'Wattlebird', nothing happens. Otherwise, do 8 damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "89",
    "name": "Wattlebird",
    "rarity": "Uncommon",
    "cost": "6C",
    "type": "Spell",
    "groupBlock": "spell",
    "descriptors": ["Password"],
    "id": 416
}, {
    "text": "To Win: Use Actions to play Spell cards 2 times while this card is in play. Prize: Loser takes 6 damage.",
    "set": "chamberOfSecrets",
    "number": "90",
    "name": "Windy-Day Match",
    "rarity": "Uncommon",
    "cost": "1Q",
    "type": "Match",
    "groupBlock": "match",
    "id": 417
}, {
    "text": "Show your hand to your opponent. Put all Lesson cards there into play.",
    "set": "chamberOfSecrets",
    "number": "91",
    "name": "Aparecium",
    "rarity": "Common",
    "cost": "5T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 418
}, {
    "text": "Do 5 damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "92",
    "name": "Backfire!",
    "rarity": "Common",
    "cost": "6C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 419
}, {
    "text": "Search your deck. You may take a Creature card from your deck, show it to your opponent and put it into your hand. Then shuffle your deck.",
    "set": "chamberOfSecrets",
    "number": "93",
    "name": "Badgered Boy",
    "rarity": "Common",
    "cost": "4T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 420
}, {
    "text": "You may use an Action and discard a card from your hand to do 2 damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "94",
    "name": "Beater's Bat",
    "rarity": "Common",
    "cost": "4Q",
    "type": "Item",
    "groupBlock": "item",
    "id": 421
}, {
    "text": "Choose 1 of your opponent's Creatures in play and discard it.",
    "set": "chamberOfSecrets",
    "number": "95",
    "name": "Beetle Buttons",
    "rarity": "Common",
    "cost": "6T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 422
}, {
    "text": "Do 3 damage to your opponent. Then, if your opponent has any cards in play (other than his or her starting Character), he or she chooses 1 of them and returns it to his or her hand.",
    "set": "chamberOfSecrets",
    "number": "96",
    "name": "Catching Apples",
    "rarity": "Common",
    "cost": "5Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 423
}, {
    "text": "You may use an Action to put up to 2 cards from your hand on the bottom of your deck (in any order).",
    "set": "chamberOfSecrets",
    "number": "97",
    "name": "Chudley Cannons Robes",
    "rarity": "Common",
    "cost": "3Q",
    "type": "Item",
    "groupBlock": "item",
    "id": 424
}, {
    "text": "To play this card, return 1 of you: Lessons from play to your hand.",
    "set": "chamberOfSecrets",
    "number": "98",
    "name": "Copper Cauldron",
    "rarity": "Common",
    "cost": "3P",
    "type": "Item",
    "groupBlock": "item",
    "descriptors": ["Cauldron"],
    "id": 425
}, {
    "text": "To play this card, return 1 of: 'Lessons from play to your hand. Do 6 damage to your opponent or to a Creature of your choice.'",
    "set": "chamberOfSecrets",
    "number": "99",
    "name": "Death Cap Draught",
    "rarity": "Common",
    "cost": "5P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 426
}, {
    "text": "During your opponent's next turn, he or she can't use Actions to play cards.",
    "set": "chamberOfSecrets",
    "number": "100",
    "name": "Deboning",
    "rarity": "Common",
    "cost": "7T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 427
}, {
    "text": "Do 4 damage to your opponent. During your opponent's next turn, he or she can't use Actions to play Quidditch cards.",
    "set": "chamberOfSecrets",
    "number": "101",
    "name": "Dizziness Draught",
    "rarity": "Common",
    "cost": "4P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 428
}, {
    "text": "Remove all damage counters from all of your Creatures in play.",
    "set": "chamberOfSecrets",
    "number": "102",
    "name": "Engorgement Charm",
    "rarity": "Common",
    "cost": "5C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 429
}, {
    "text": "Choose a Creature or Lesson in play and discard it.",
    "set": "chamberOfSecrets",
    "number": "103",
    "name": "Evanesce",
    "rarity": "Common",
    "cost": "7T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 430
}, {
    "text": "To play this card, return 1 of your Creatures in play to your hand.Damage: 2 Health: 2",
    "set": "chamberOfSecrets",
    "number": "104",
    "name": "Family Ghoul",
    "rarity": "Common",
    "cost": "3F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Ghoul"],
    "id": 431
}, {
    "text": "To play this card, return 1 of you: Lessons from play to your hand. Do 9 damage to your opponent or to a Creature of your choice.",
    "set": "chamberOfSecrets",
    "number": "105",
    "name": "Fatiguing Fusion",
    "rarity": "Common",
    "cost": "8P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 432
}, {
    "text": "Do 2 damage to your opponent. Then, if your opponent has any cards in his or her hand, he or she chooses 1 of them and discards it.",
    "set": "chamberOfSecrets",
    "number": "106",
    "name": "Flacking",
    "rarity": "Common",
    "cost": "3Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 433
}, {
    "text": "Do 4 damage to your opponent or to a Creature of your choice.",
    "set": "chamberOfSecrets",
    "number": "107",
    "name": "Freezing Charm",
    "rarity": "Common",
    "cost": "7C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 434
}, {
    "text": "At the end of each of your opponent's turns, if there are any cards in his or her hand, he or she chooses 1 of them and discards it.Damage: 0 Health: 1",
    "set": "chamberOfSecrets",
    "number": "108",
    "name": "Garden Gnome",
    "rarity": "Common",
    "cost": "4F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Gnome"],
    "id": 435
}, {
    "text": "Damage: 3 Health: 3",
    "set": "chamberOfSecrets",
    "number": "109",
    "name": "Gryffindor Lion",
    "rarity": "Common",
    "cost": "6F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Lion","Gryffindor"],
    "id": 436
}, {
    "text": "You may use an Action and discard this card from play to choose a Creature in play and do 4 damage to it. Provide: ",
    "set": "chamberOfSecrets",
    "number": "110",
    "name": "Guide to Household Pests",
    "rarity": "Common",
    "cost": "2F",
    "type": "Item",
    "groubBlock": "item",
    "descriptors": ["Book"],
    "id": 437
}, {
    "text": "Do 1 damage to your opponent or to a Creature of your choice.",
    "set": "chamberOfSecrets",
    "number": "111",
    "name": "Hair-Raising Potion",
    "rarity": "Common",
    "cost": "3P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 438
}, {
    "text": "Do 6 damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "112",
    "name": "Hawkshead Formation",
    "rarity": "Common",
    "cost": "7Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 439
}, {
    "text": "Discard the Adventure your opponent has played. You get the reward.",
    "set": "chamberOfSecrets",
    "number": "113",
    "name": "Hermione's Note",
    "rarity": "Common",
    "cost": "6C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 440
}, {
    "text": "Search your deck. You may take a Lesson card from your deck and put it into play. Then shuffle your deck.",
    "set": "chamberOfSecrets",
    "number": "114",
    "name": "History of Magic Homework",
    "rarity": "Common",
    "cost": "3T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 441
}, {
    "text": "Choose 1 of your opponent's cards in play (other than his or her starting Character) and return it to his or her hand.",
    "set": "chamberOfSecrets",
    "number": "115",
    "name": "Hover Charm",
    "rarity": "Common",
    "cost": "4C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 442
}, {
    "text": "Do 2 damage to your opponent. Then, if your opponent has any cards in his or her hand, look at them. Choose 1 of those cards and put it on top of his or her deck.",
    "set": "chamberOfSecrets",
    "number": "116",
    "name": "Howler",
    "rarity": "Common",
    "cost": "4C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 443
}, {
    "text": "Damage:1Health:3",
    "set": "chamberOfSecrets",
    "number": "117",
    "name": "Hufflepuff Badger",
    "rarity": "Common",
    "cost": "3F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Badger", "Hufflepuff"],
    "id": 444
}, {
    "text": "Choose up to 2 Lessons in play and discard them.",
    "set": "chamberOfSecrets",
    "number": "118",
    "name": "Invisible Ink",
    "rarity": "Common",
    "cost": "8T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 445
}, {
    "text": "Once per turn, you may let Leaping Toadstools take 1 damage that you were going to take.Damage: 0 Health: 4",
    "set": "chamberOfSecrets",
    "number": "119",
    "name": "Leaping Toadstools",
    "rarity": "Common",
    "cost": "1F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Plant"],
    "id": 446
}, {
    "text": "Look at your opponent's hand. Count the number of Lesson cards there. Do that much damage to your opponent.",
    "set": "chamberOfSecrets",
    "number": "120",
    "name": "Overdue Homework",
    "rarity": "Common",
    "cost": "2C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 447
}, {
    "text": "Put up to 4 non-Healing cards from your discard pile on the bottom of your deck (in any order).",
    "set": "chamberOfSecrets",
    "number": "121",
    "name": "Pepperup Potion",
    "rarity": "Common",
    "cost": "1P",
    "type": "Spell",
    "groupBlock": "spell",
    "descriptors": ["Healing"],
    "id": 448
}, {
    "text": "Your opponent takes damage until he or she discards a Lesson card from his or her deck.",
    "set": "chamberOfSecrets",
    "number": "122",
    "name": "Potions Homework",
    "rarity": "Common",
    "cost": "3P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 449
}, {
    "text": "Your opponent chooses 2 cards in his or her hand and discards them (1 if he or she has only 1).",
    "set": "chamberOfSecrets",
    "number": "123",
    "name": "Ransacked!",
    "rarity": "Common",
    "cost": "5C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 450
}, {
    "text": "Damage: 2  Health: 2",
    "set": "chamberOfSecrets",
    "number": "124",
    "name": "Ravenclaw Eagle",
    "rarity": "Common",
    "cost": "4F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Eagle", "Ravenclaw"],
    "id": 451
}, {
    "text": "Do 4 damage to your opponent. During your opponent's next turn, he or she can't use Actions to play Transfiguration cards.",
    "set": "chamberOfSecrets",
    "number": "125",
    "name": "Restoration Potion",
    "rarity": "Common",
    "cost": "4P",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 452
}, {
    "text": "You may use an Action to look at your opponent's hand.",
    "set": "chamberOfSecrets",
    "number": "126",
    "name": "Revealer",
    "rarity": "Common",
    "cost": "2T",
    "type": "Item",
    "groupBlock": "item",
    "id": 453
}, {
    "text": "Do 2 damage to your opponent or to a Creature of your choice. Then draw a card.",
    "set": "chamberOfSecrets",
    "number": "127",
    "name": "Rose Growth",
    "rarity": "Common",
    "cost": "3C",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 454
}, {
    "text": "You may use an Action and discard a card from your hand to draw 2 cards. If you play this card, and you already have a Broom in play, discard the old one.",
    "set": "chamberOfSecrets",
    "number": "128",
    "name": "Shooting Star",
    "rarity": "Common",
    "cost": "4Q",
    "type": "Item",
    "groupBlock": "item",
    "descriptors": ["Broom"],
    "id": 455
}, {
    "text": "When you play this card, draw a card.<p>Damage: 1  Health: 1</p>",
    "set": "chamberOfSecrets",
    "number": "129",
    "name": "Slinking Ferret",
    "rarity": "Common",
    "cost": "3F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Ferret"],
    "id": 456
}, {
    "text": "Before each of your turns, your opponent takes 1 damage.",
    "set": "chamberOfSecrets",
    "number": "130",
    "name": "Slow-Acting Venom",
    "rarity": "Common",
    "cost": "6P",
    "type": "Item",
    "groupBlock": "item",
    "id": 457
}, {
    "text": "Damage: 3  Health: 1",
    "set": "chamberOfSecrets",
    "number": "131",
    "name": "Slytherin Serpent",
    "rarity": "Common",
    "cost": "5F",
    "type": "Creature",
    "groupBlock": "creature",
    "descriptors": ["Snake", "Slytherin"],
    "id": 458
}, {
    "text": "Do 2 damage to your opponent. Then, if your opponent has any cards in play (other than his or her starting Character), he or she chooses 1 of them and discards it.",
    "set": "chamberOfSecrets",
    "number": "132",
    "name": "Slytherin Steals",
    "rarity": "Common",
    "cost": "5Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 459
}, {
    "text": "Draw 2 cards. Then you may put up to 2 Lesson cards from your hand into play.",
    "set": "chamberOfSecrets",
    "number": "133",
    "name": "Training Programme",
    "rarity": "Common",
    "cost": "7Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 460
}, {
    "text": "Choose 1 of your opponent's Items in play and put it on the bottom of his or her deck.",
    "set": "chamberOfSecrets",
    "number": "134",
    "name": "Vanishing Cabinet",
    "rarity": "Common",
    "cost": "1T",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 461
}, {
    "text": "Put a non-Healing Quidditch card from your discard pile into your hand.",
    "set": "chamberOfSecrets",
    "number": "135",
    "name": "Zig-Zag",
    "rarity": "Common",
    "cost": "5Q",
    "type": "Spell",
    "groupBlock": "spell",
    "id": 462
}]